collector:
  interface: "0.0.0.0"
  port: 8080
  paths:
    # Example Kafka sink configuration
    "/com.acme/":
      method: "POST"
      good: "kafka-broker:9092"
      bad: "kafka-broker:9092"
      useIpAddressAsKey: true
      encoder: "json"
      appName: "my-scala-stream-collector"
